kind: Service
apiVersion: v1

metadata:
  name: bankapp-service
  namespace: bankapp

spec:
  type: NodePort
  selector:
    app: bankapp
  ports:
    - port: 8080 # you want to run app on which port on host machine 
      targetPort: 8080  # app ruuning on port inside pod on 8080 port
  
    