kind: Service
apiVersion: v1

metadata:
  name: bankapp-service
  namespace: bankapp

spec:
  type: NodePort
  selector:
    app: bankapp
  ports:
    - port: 8080 # This is your service port  
      targetPort: 8080 # port inside container i.e deployment port 
      nodePort: 30080  # this is worker node port 


    