apiVersion: apps/v1
kind: Deployment

metadata:
  name: mysql-deployment
  namespace: bankapp
  labels:
    app: mysql
  

spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: mysql

  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql-cont
        image: mysql:8.0
        ports:
        - containerPort: 3306

        # declaring env & secret variable  from configMap & secrets
        env:

          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: bankapp-configmap      # this vlaue comes from  ConfigMap 
                key: MYSQL_DATABASE          # The key to fetch.
        
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: bankapp-secrets
                key: MYSQL_ROOT_PASSWORD
        
        # declaring volume from pv & pvc 
        volumeMounts:
        - name: mysql-vol
          mountPath: /var/lib/mysql

        # declaring healcheck in k8s used probes
        readinessProbe:
          exec:
            command: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
          initialDelaySeconds: 15
          periodSeconds: 10

      volumes:
        - name: mysql-vol
          persistentVolumeClaim:
            claimName: mysql-pvc
              